# Generated by Django 4.0 on 2024-02-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bvs_educationlevel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationlevel',
            name='education_level',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
