# Generated by Django 4.2.4 on 2023-08-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bvs_treatment', '0002_treatment_current_status_treatment_dischared_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='dischared_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='expired_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='hospitalized_date',
            field=models.DateTimeField(null=True),
        ),
    ]
