# Generated by Django 4.0 on 2023-09-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bvs_treatment', '0003_alter_treatment_dischared_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='current_status',
        ),
        migrations.AddField(
            model_name='treatment',
            name='distance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='duration_of_stay',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='medical_support',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='mode_of_transport',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='no_of_amputation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='no_of_debridement',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='no_of_dressing',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='no_of_nutritional',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='no_of_skin_graft',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='no_of_surgery',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='dischared_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='expired_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='hospital',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='hospitalized_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
