# Generated by Django 4.0 on 2023-10-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bvs_treatment', '0005_treatment_is_post_treatment'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
