# Generated by Django 4.0 on 2024-02-05 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bvs_hospital', '0001_initial'),
        ('bvs_treatment', '0006_treatment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bvs_hospital.hospital'),
        ),
    ]
