# Generated by Django 4.0 on 2024-02-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bvs_treatment', '0008_alter_treatment_dischared_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='dischared_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='expired_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='hospitalized_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
