# Generated by Django 4.0 on 2024-02-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bvs_treatment', '0009_alter_treatment_dischared_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='mode_of_transport',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
