# Generated by Django 4.0 on 2023-09-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bvs_question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='questionnaire',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
