# Generated by Django 4.0 on 2023-10-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bvs_user', '0003_alter_user_location_alter_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
