# Generated by Django 4.2.4 on 2023-08-22 10:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('registration_date', models.DateField()),
                ('fiscal_year', models.CharField(blank=True, max_length=10)),
                ('registration_location', models.CharField(max_length=100)),
                ('registration_number', models.CharField(blank=True, max_length=20, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
