# Generated by Django 4.2.4 on 2023-08-27 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bvs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
