# Generated by Django 4.2.4 on 2023-08-27 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bvs', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Occupation',
        ),
    ]
