# Generated by Django 4.0 on 2023-10-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bvs_donor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='donor_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
