# Generated by Django 4.0 on 2024-02-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bvs_pshychosocial', '0002_psychosocial_number_of_counseling_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychosocial',
            name='followed_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
