# Generated by Django 4.0 on 2023-09-24 07:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bvs_question', '0002_alter_question_questionnaire'),
        ('bvs_patient', '0009_alter_patient_burn_cause_alter_patient_burn_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reintegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bvs_patient.patient')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bvs_question.question')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
