# Generated by Django 4.2.4 on 2023-08-29 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bvs_occupation', '0001_initial'),
        ('bvs_patient', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='parents_occupation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='bvs_occupation.occupation'),
        ),
    ]
