# Generated by Django 4.0 on 2023-09-07 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bvs_burncause', '0001_initial'),
        ('bvs_burntype', '0001_initial'),
        ('bvs_patient', '0006_alter_patient_mname'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='country2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='district2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='echo_other',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='economic_status',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='epilepsy',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='family_support',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='foreign_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='foreign_address2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='hiv_positive',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='lactating_mother',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='local2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='mental_illness',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='month_at_incident',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='optional_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_education',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='person_at_hospital',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='person_contact',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='pregnant_women',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='provence2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='relation_to_parent',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='tole2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='ward2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='with_disabilities',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age_at_incident',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='area_of_burn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='cause_of_burn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bvs_burncause.burncause'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='citizenship_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='country',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='description_of_incident',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='district',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='local',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='number_of_child',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='number_of_siblings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='parents_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='place_of_incident',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='provence',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tole',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='type_of_burn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bvs_burntype.burntype'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ward',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
