# Generated by Django 4.0 on 2023-09-07 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bvs_patient', '0007_patient_country2_patient_district2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='cause_of_burn',
            new_name='burn_cause',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='type_of_burn',
            new_name='burn_type',
        ),
    ]
