# Generated by Django 4.0 on 2023-10-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bvs_patient', '0009_alter_patient_burn_cause_alter_patient_burn_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age_group',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='day_at_incident',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
