# Generated by Django 4.0 on 2023-10-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bvs_patient', '0010_patient_age_group_patient_day_at_incident_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
