# Generated by Django 4.0 on 2024-02-06 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bvs_language', '0001_initial'),
        ('bvs_patient', '0012_alter_patient_patient_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bvs_language.language'),
        ),
    ]
