# Generated by Django 4.0 on 2024-02-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bvs_patient', '0015_alter_patient_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_of_incident',
            field=models.DateField(null=True),
        ),
    ]
