# Generated by Django 4.0 on 2024-02-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bvs_patient', '0016_alter_patient_date_of_incident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_incident',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
