# Generated by Django 4.0 on 2024-02-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bvs_language', '0001_initial'),
        ('bvs_patient', '0017_alter_patient_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='patient_language',
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_language',
            field=models.ManyToManyField(blank=True, to='bvs_language.Language'),
        ),
    ]
