# Generated by Django 4.2.4 on 2023-08-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bvs_funding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='funding_amount',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
    ]
