# Generated by Django 4.2.4 on 2023-08-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bvs_donor', '0001_initial'),
        ('bvs_funding', '0002_alter_funding_funding_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funding',
            name='donor',
        ),
        migrations.AddField(
            model_name='funding',
            name='donor',
            field=models.ManyToManyField(to='bvs_donor.donor'),
        ),
    ]
