# Generated by Django 4.2.4 on 2023-08-28 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bvs_donor', '0001_initial'),
        ('bvs_funding', '0003_remove_funding_donor_funding_donor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funding',
            name='donor',
        ),
        migrations.AddField(
            model_name='funding',
            name='donor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='bvs_donor.donor'),
        ),
    ]
