# Generated by Django 4.0 on 2024-02-06 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bvs_donor', '0002_alter_donor_donor_address'),
        ('bvs_funding', '0006_funding_service_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bvs_donor.donor'),
        ),
        migrations.AlterField(
            model_name='funding',
            name='funding_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
    ]
