# Generated by Django 4.0 on 2024-02-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bvs_funding', '0007_alter_funding_donor_alter_funding_funding_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='service_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
