# Generated by Django 4.2.4 on 2023-08-28 15:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bvs_patient', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Physiotherapy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('initial_status', models.TextField(null=True)),
                ('applied_methods', models.TextField(null=True)),
                ('dischared_status', models.TextField(null=True)),
                ('observation', models.TextField(null=True)),
                ('current_status', models.TextField(null=True)),
                ('mode_of_followup', models.TextField(null=True)),
                ('followed_by', models.CharField(max_length=100, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bvs_patient.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
