# Generated by Django 4.0 on 2024-02-06 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bvs_followUpSummary', '0001_initial'),
        ('bvs_physiotherapy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='physiotherapy',
            name='followup_summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bvs_followUpSummary.followupsummary'),
        ),
        migrations.AddField(
            model_name='physiotherapy',
            name='number_of_session',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physiotherapy',
            name='applied_methods',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physiotherapy',
            name='current_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physiotherapy',
            name='dischared_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physiotherapy',
            name='followed_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='physiotherapy',
            name='initial_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physiotherapy',
            name='mode_of_followup',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physiotherapy',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
